export enum ActionType {
    SET_DASHBOARD_STATE,
    OPEN_DASHBOARD,
    SAVE_DASHBOARD,
    TOGGLE_COMPACTION,
    LAYOUT_CHANGE,
    DUPLICATE_WIDGET,
    DELETE_WIDGET,
    SET_DASHBOARD_SETIINGS,
    SET_SERIES_DATA,
    FETCH_SERIES_DATA
}